### ISSUE TITLE
issue with VIM website not detect my computer

### ISSUE THREAD

**Issue by VlSUALPURPLE** [colinhartigan/valorant-inventory-manager#101]
i open vim.exe and run it and it says server is running please visit the website and i visit it and it says this 
dont know why it reads my account info and region correctly but says this error
https://imgur.com/a/tKgJhiI

**Comment by Felfuwastaken** [comment]
same happens to me

**Comment by VlSUALPURPLE** [comment]
> same happens to me

lol maybe its just on the devs side then idk what the deal is

**Comment by colinhartigan** [comment]
delete the folder `%APPDATA%\valorant-inventory-manager` then try running the client companion again

**Comment by colinhartigan** [comment]
should be fixed, use [this patched client](https://github.com/colinhartigan/valorant-inventory-manager/releases/download/v1.2/VIM.exe)
