### ISSUE TITLE
VIM crashes as soon as i open the web client

### ISSUE THREAD

**Issue by Perrytos99** [colinhartigan/valorant-inventory-manager#102]
![image](https://github.com/colinhartigan/valorant-inventory-manager/assets/125727939/ca2062ba-e8b6-42a5-97dc-b77082f2ec5b)
First time ever opening an issue, so sorry if its lackluster. After doing the setup just fine this popped up on the terminal. By itself the executable runs just fine, but as soon as i open the web client it crashes. Everytime i try to subsequently reopen the web client, this error shows up, always the same.

**Comment by colinhartigan** [comment]
delete the folder `%APPDATA%\valorant-inventory-manager` then try running again

**Comment by colinhartigan** [comment]
#101
