### ISSUE TITLE
Error when saving Protocol skins with level set lower than 5

### ISSUE THREAD

**Issue by Sythiex** [colinhartigan/valorant-inventory-manager#103]
Updated VIM to v1.2, configured 3 sheriff skins to randomize, when I click X/Save on the sheriff window VIM throws this error:
```
2023-05-12 14:05:13,707 [ERROR] VIM_errors: ----- EXCEPTION -----
2023-05-12 14:05:13,708 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\server.py", line 126, in ws_entrypoint
  File "src\inventory_management\profile_manager.py", line 116, in update_profile
TypeError: unhashable type: 'dict'
```
~~I _think_ it might have something to do with the Protocol skin as I've only gotten the error when Protocol is added to the randomize pool~~ Seems to be caused by the Protocol skins when they are set at a level lower than 5. Screenshot below shows the settings I have selected right before the error.
![image](https://github.com/colinhartigan/valorant-inventory-manager/assets/14610458/c6089046-bb23-4706-9eaa-f1d409a42742)

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.2.1
