### ISSUE TITLE
Can't click on guns that have "Random Favorite Skin" on

### ISSUE THREAD

**Issue by ecraa** [colinhartigan/valorant-inventory-manager#104]
I've tried changing skins in game with VIM on and off and restarting valorant 

https://github.com/colinhartigan/valorant-inventory-manager/assets/101248645/c253853c-d4a2-4155-81d6-e34d5f4774f1

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.2.1
