### ISSUE TITLE
Error when saving skin favorites

### ISSUE THREAD

**Issue by UnnamedYTr** [colinhartigan/valorant-inventory-manager#106]
ERROR:VIM_errors:Traceback (most recent call last):
  File "src\server.py", line 126, in ws_entrypoint
  File "src\inventory_management\profile_manager.py", line 116, in update_profile
TypeError: unhashable type: 'dict'

This error come up after trying to save a skin chroma to the favorites or remove them.

**Comment by UnnamedYTr** [comment]
It always happens when trying to use a level or chroma that isn't the highest available.

**Comment by colinhartigan** [comment]
i'm not able to replicate this, try deleting `%APPDATA%/valorant-inventory-manager` and starting over

**Comment by colinhartigan** [comment]
duplicate of #103
