### ISSUE TITLE
Different Accounts

### ISSUE THREAD

**Issue by SHIKAIMOON** [colinhartigan/valorant-inventory-manager#110]
It seems like I've accidentally used the wrong account for the VIM. I loaded up my second account which doesn't have any skins and now im wondering if there's a way to switch to my main, since you can't seem to change accounts after selecting one

**Comment by SHIKAIMOON** [comment]
![image](https://github.com/colinhartigan/valorant-inventory-manager/assets/138085377/78f4ae51-b825-4e51-a45e-cc846540b287)

**Comment by colinhartigan** [comment]
delete the folder `%APPDATA%/valorant-inventory-manager` to reset everything
