### ISSUE TITLE
In the https://colinhartigan.github.io/valorant-inventory-manager, the skins do not show up for me, it only shows my skins which i have.

### ISSUE THREAD

**Issue by Tinymaster21** [colinhartigan/valorant-inventory-manager#13]

**Comment by AndreiNew2** [comment]
что делать?

**Comment by crypto0007** [comment]
same with me

**Comment by JezZiK** [comment]
same with me 2, we need update I am kinda excited and cannot wait for it :::

**Comment by colinhartigan** [comment]
it only shows the skins you own

**Comment by crypto0007** [comment]
> it only shows the skins you own

But why? Is it a bug?
Than what do if we own some skins?

**Comment by crypto0007** [comment]
> it only shows the skins you own

In the video, the YouTuber is saying that we can get skins by owning them and here u r telling that we need to have the skins?
