### ISSUE TITLE
Connection failed and Key error

### ISSUE THREAD

**Issue by Ruchith07** [colinhartigan/valorant-inventory-manager#15]
![Screenshot 2022-02-11 132450](https://user-images.githubusercontent.com/98446189/153555420-787fe952-9f5c-4372-aa45-5debe72c5554.png)

**Comment by Ruchith07** [comment]
![image](https://user-images.githubusercontent.com/98446189/153556350-f3469768-59b1-4cbc-8362-098fe13b52e1.png)

This is also showing up in the browser

**Comment by colinhartigan** [comment]
if you have REFUNDED a skin, go in the collection page and equip the default version of the weapon, then try again

**Comment by TropicalSpoon1969** [comment]
Thankyou for reply I’ve fixed this issue actually i read your old post and then i saw I’m opening this before opening valo so that was the issue thankyou soo much for reply now it’s working fine

**Comment by colinhartigan** [comment]
great to hear
