### ISSUE TITLE
The first time I started it and such an error came out, I did everything as stated in the instructions

### ISSUE THREAD

**Issue by KUL1ER** [colinhartigan/valorant-inventory-manager#24]
![image](https://user-images.githubusercontent.com/99520012/153693549-37594814-f79c-4ab6-8ba2-eb5e1610dc46.png)

**Comment by smwlks** [comment]
나도 나옴 몇 시간 동안
 이러고 있음

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b2
