### ISSUE TITLE
cant change skins

### ISSUE THREAD

**Issue by SomeoneLMAO** [colinhartigan/valorant-inventory-manager#25]
Hello, i have this problem that i cant change any skin and i can change skins that i had already obtain and sometimes i can go through the VIM website but sometimes it says connection error.

**Comment by colinhartigan** [comment]
you can only do stuff with skins you own

**Comment by crypto0007** [comment]
> you can only do stuff with skins you own

In the video, the YouTuber is saying that we can get skins by owning them and here u r telling that we need to have the skins?
