### ISSUE TITLE
3 malicious things found by virustotal? (Why did it say 3 trojan on virustotal.com download VIM.exe and scan it on virustotal and it said Trojan.Gen.9?)

### ISSUE THREAD

**Issue by SeanPrado** [colinhartigan/valorant-inventory-manager#34]
.

**Comment by colinhartigan** [comment]
it's a false positive, but i've also included [instructions for building from source](https://github.com/colinhartigan/valorant-inventory-manager#building-the-server-from-source) if you'd rather do that
