### ISSUE TITLE
Uhm windows protected me?

### ISSUE THREAD

**Issue by SeanPrado** [colinhartigan/valorant-inventory-manager#40]
I tried to open VIM.exe when windows said Windows Protected YOUR PC and there is no open anyway only Don't Run
![2022-03-03](https://user-images.githubusercontent.com/93509907/156476507-c263d395-18d2-4450-b0af-0f956d2a3053.png)
d

**Comment by SeanPrado** [comment]
Help pl

**Comment by BakiKral38** [comment]
Press more info and press run anyway

**Comment by BakiKral38** [comment]
Press more info and press run anyway
