### ISSUE TITLE
I don't see any other skins other than my own on the site

### ISSUE THREAD

**Issue by KUL1ER** [colinhartigan/valorant-inventory-manager#41]
I launch the loader, everything goes well, but only my skins are shown on the site
![image](https://user-images.githubusercontent.com/99520012/156572341-8f76057e-d4a3-41e3-ba86-d70efbd91cfa.png)
![image](https://user-images.githubusercontent.com/99520012/156572649-e36a1242-1fb8-4a0a-a4ed-f75174593767.png)

**Comment by Fahad5011** [comment]
me too , did you fixit?  i need your help

**Comment by KUL1ER** [comment]
as I understand it, this is not a skinchanger, just a site for randomizing skins
