### ISSUE TITLE
No Skin

### ISSUE THREAD

**Issue by BakiKral38** [colinhartigan/valorant-inventory-manager#42]
I'm doing it on the web as in the video, but I thought I'd choose there are no skins, it doesn't work either.
![image](https://user-images.githubusercontent.com/101063272/156937140-cd6ce8d1-bf05-47d0-8022-23922da3313e.png)

**Comment by recur74** [comment]
You need to restart vim.exe if you just bought a new skin. Valorant needs to be started before vim.exe.

**Comment by colinhartigan** [comment]
need to own skins
