### ISSUE TITLE
I don't have skins, help!

### ISSUE THREAD

**Issue by Looz1x** [colinhartigan/valorant-inventory-manager#44]
![image](https://user-images.githubusercontent.com/101524123/158075111-ee89b193-4de8-4169-ad6e-fa3805bf8529.png)

**Comment by xmediym** [comment]
ты что русский

**Comment by xmediym** [comment]
тебе нужно иметь скины это не  скин ченджер

**Comment by xmediym** [comment]
это свапер который заменяет скины на другой скин

**Comment by colinhartigan** [comment]
please read. https://github.com/colinhartigan/valorant-inventory-manager#this-is-not-a-skin-hack-it-does-not-give-you-free-skins
