### ISSUE TITLE
Key error:latam

### ISSUE THREAD

**Issue by Pierxdal** [colinhartigan/valorant-inventory-manager#5]
I play on the Santiago servers and this error appeared, is the mod available for Latin America? How can I solve the error?
![image](https://user-images.githubusercontent.com/99452771/153520974-dcb6f251-8099-4bfd-9614-7bf6359a724c.png)

**Comment by colinhartigan** [comment]
delete `%APPDATA%/valorant-inventory-manager`

**Comment by colinhartigan** [comment]
i think i have identified the cause and will publish a fix soon

**Comment by colinhartigan** [comment]
duplicate of #7, closing
