### ISSUE TITLE
There are no skins to choose from

### ISSUE THREAD

**Issue by Yazva08** [colinhartigan/valorant-inventory-manager#53]
When you click on a weapon, there is not a single skin. What to do with it?
![image](https://user-images.githubusercontent.com/102324339/159995005-c2875476-9adb-4da9-97e8-d4c2e52e3e93.png)

**Comment by colinhartigan** [comment]
you need to own skins

**Comment by MHL-HOOMAN** [comment]
i have the same issue but i have skins
