### ISSUE TITLE
vim no longer suport

### ISSUE THREAD

**Issue by EteryIsHere** [colinhartigan/valorant-inventory-manager#61]
Your VIM client companion version is no longer supported. (1.0.0b2 → v1.0.0b3)  but i take last version

**Comment by Jakacp** [comment]
I have a problem because when I go to the vim website I don't have skins, I don't know why I am asking for help

**Comment by colinhartigan** [comment]
https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.0.0b3
