### ISSUE TITLE
Client Companion version mismatch Your VIM client companion version is no longer supported. (1.0.0b2 → v1.0.0b3)

### ISSUE THREAD

**Issue by selimcdrx** [colinhartigan/valorant-inventory-manager#64]
Client Companion version mismatch
Your VIM client companion version is no longer supported. (1.0.0b2 → v1.0.0b3) 

i have a problem what is the solution

**Comment by ghoul616** [comment]
![image](https://user-images.githubusercontent.com/104700237/166126298-62210d7d-2c9b-432a-9330-1106bf0941b7.png)
There are no skins on the site. What should I do?

**Comment by qualk** [comment]
> ![image](https://user-images.githubusercontent.com/104700237/166126298-62210d7d-2c9b-432a-9330-1106bf0941b7.png) There are no skins on the site. What should I do?

Holy shit did you not read the first line in the GitHub???
### **THIS IS NOT A SKIN "HACK". IT DOES NOT GIVE YOU FREE SKINS.**
It manages your current skins. It is called "Valorant Inventory Manager", not "Valorant Skin Changer"

**Comment by qualk** [comment]
> Client Companion version mismatch Your VIM client companion version is no longer supported. (1.0.0b2 → v1.0.0b3)
> 
> I have a problem what is the solution

[Download](https://github.com/colinhartigan/valorant-inventory-manager/releases/download/v1.0.0b3/VIM.exe) the latest version, and try again @ghoul616.

**Comment by Gani200** [comment]
same problem for me also

**Comment by Gani200** [comment]
-  - [ ] ### **#[
![1](https://user-images.githubusercontent.com/105498012/168285300-1317046d-f8f4-4adf-a66a-736d8391a2e1.png)
](url)**

**Comment by qualk** [comment]
> > ![image](https://user-images.githubusercontent.com/104700237/166126298-62210d7d-2c9b-432a-9330-1106bf0941b7.png) There are no skins on the site. What should I do?
> 
> Holy shit did you not read the first line in the GitHub???
> 
> ### **THIS IS NOT A SKIN "HACK". IT DOES NOT GIVE YOU FREE SKINS.**
> It manages your current skins. It is called "Valorant Inventory Manager", not "Valorant Skin Changer"
@Gani200
