### ISSUE TITLE
Don't have skins

### ISSUE THREAD

**Issue by danbbn** [colinhartigan/valorant-inventory-manager#66]
there are no skins in the site
![image](https://user-images.githubusercontent.com/104784434/166286428-d34c7a95-1eb9-48b0-b731-d1c863b5905f.png)

**Comment by mtyyoussef9** [comment]
yeah me to

**Comment by KcTec90** [comment]
Fun fact: YOU DON'T GET FREE SKINS FROM THIS :DDDD
