### ISSUE TITLE
Rgx firefly knife

### ISSUE THREAD

**Issue by OzymoGit** [colinhartigan/valorant-inventory-manager#68]
Is the a way to chose exactly a color for the rgb outline

**Comment by qualk** [comment]
Can you select the variants of the knife? I cant test because I don't have it ;-;

**Comment by OzymoGit** [comment]
> Can you select the variants of the knife? I cant test because I don't have it ;-;

I mean the rgb light not the variants. Its randomized everytime u inspect.

**Comment by qualk** [comment]
Oh... nothing can change the RGB. Well, except for Riot.
Please close the issue.
