### ISSUE TITLE
cant seegun skin 

### ISSUE THREAD

**Issue by nimmi-cell** [colinhartigan/valorant-inventory-manager#73]
can any one help me i can see any gun skins

**Comment by nimmi-cell** [comment]
in my web client

**Comment by nimmi-cell** [comment]
![image](https://user-images.githubusercontent.com/106403970/170772183-eb270d5a-fc35-4a15-89de-37388f1a47a3.png)

**Comment by NicoJ123** [comment]
Та же самая проблема

**Comment by qualk** [comment]
@nimmi-cell https://github.com/colinhartigan/valorant-inventory-manager#this-is-not-a-skin-hack-it-does-not-give-you-free-skins

**Comment by grefory-b** [comment]
такая же проблема

**Comment by xpobpobp** [comment]
Same problem, please help.

**Comment by qualk** [comment]
> Same problem, please help.

Can none of you read?

**Comment by qualk** [comment]
> If you have no skins, it won't show... I can read :) 
@KcTec90 les goo
