### ISSUE TITLE
It doesn't show me any skin

### ISSUE THREAD

**Issue by Kiyt03** [colinhartigan/valorant-inventory-manager#74]
I did the download correctly and I started again several times but still nothing I tried the trick of step 2 but still! Is there a problem because I come from France maybe?
![image_2022-05-29_223524680](https://user-images.githubusercontent.com/106492466/170890478-74a866d9-dce5-4995-b892-1987c3685213.png)

**Comment by qualk** [comment]
THIS IS NOT A SKIN "HACK". IT DOES NOT GIVE YOU FREE SKINS.

This is not a Skin Changer or any sort of hack, IT MANAGES THE SKINS YOU OWN.
@Kiyt03

**Comment by grefory-b** [comment]
your page doesn't show me skins either, it's also just empty, I can't choose a skin why?

**Comment by qualk** [comment]
People's vision are so good these days.
