### ISSUE TITLE
I don't have skins

### ISSUE THREAD

**Issue by Nikita15mail** [colinhartigan/valorant-inventory-manager#81]
![image](https://user-images.githubusercontent.com/109981241/180833238-60d5cce4-745a-4259-8639-3f5cc4ed5201.png)

**Comment by harshastark** [comment]
same issue no skins in it

**Comment by default868** [comment]
the same

**Comment by dima20065** [comment]
toje

**Comment by colinhartigan** [comment]
you gotta own skins
