### ISSUE TITLE
where are the skins?

### ISSUE THREAD

**Issue by rozetka41** [colinhartigan/valorant-inventory-manager#82]
no skins
![изображение](https://user-images.githubusercontent.com/110136171/181381087-3f334d62-3d1a-4030-b068-f91068709c32.png)

**Comment by shiniwaifu** [comment]
i can not see my skins what i have to do

**Comment by DAEMON41** [comment]
+, no skins too

**Comment by default868** [comment]
the same

**Comment by colinhartigan** [comment]
you gotta own skins
