### ISSUE TITLE
Don't See The Skins

### ISSUE THREAD

**Issue by smitdudhat** [colinhartigan/valorant-inventory-manager#86]
![image](https://user-images.githubusercontent.com/94129032/184330945-41853158-fd6c-447a-94c0-27d01577f90d.png)

**Comment by colinhartigan** [comment]
you gotta own skins

**Comment by smitdudhat** [comment]
So you want say you can change or shuffle your own skins. not all the skins.  right?

**Comment by qualk** [comment]
Yes.

**Comment by smitdudhat** [comment]
Okay Thanks!!
