### ISSUE TITLE
i dont have skins in my inventory

### ISSUE THREAD

**Issue by luxebunny** [colinhartigan/valorant-inventory-manager#87]
i dont have skins in my inventory
![image](https://user-images.githubusercontent.com/111681658/185784000-df076730-d88c-4f7d-b362-1bf951b513d9.png)
![image](https://user-images.githubusercontent.com/111681658/185784008-2e0f6a8b-e005-4066-ae1f-e2882bb88215.png)

**Comment by colinhartigan** [comment]
you gotta own skins
