### ISSUE TITLE
Flagging windows defender firewall - inoperable

### ISSUE THREAD

**Issue by qwak-adikt** [colinhartigan/valorant-inventory-manager#89]
WDF always has issue with unsigned exe's but in this case it appears the latest version of VIM is not allowed to execute on Windows 10 due to being flagged for a virus or malicious code.

I did run it against virustotal and it came back clean but as for now at least some of us cannot open the file at all in the W10 environment

**Comment by colinhartigan** [comment]
works fine on windows 11... not really sure how to approach this problem. isn't there a way to manually whitelist stuff through wdf?

**Comment by gnpfun** [comment]
I'm have the same issue but on windows 11. Its detecting a virus and won't let me download VIM.exe. any advice cause i love this program

**Comment by colinhartigan** [comment]
you can try adding it as an exclusion: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
