### ISSUE TITLE
I don,t have any skin on the website

### ISSUE THREAD

**Issue by Kami3va** [colinhartigan/valorant-inventory-manager#9]
![image](https://user-images.githubusercontent.com/99460784/153535173-6809c334-836b-4a15-b382-289760422150.png)
idk why I dont have any skins

**Comment by Kami3va** [comment]
did I do something wrong ?

**Comment by colinhartigan** [comment]
you have to own skins

**Comment by Kami3va** [comment]
ty ty, someone told me on discord :D
