### ISSUE TITLE
skins not working nor appear in web

### ISSUE THREAD

**Issue by shadowja22** [colinhartigan/valorant-inventory-manager#90]
![VIM __ Bulldog and 4 more pages - Personal - Microsoft​ Edge 9_4_2022 5_04_24 AM](https://user-images.githubusercontent.com/112788927/188294150-dd767805-9b46-4193-a9ac-292862f5c880.png)

**Comment by ALMANE1** [comment]
me too

**Comment by S1avyanin** [comment]
how to fix

**Comment by Jiji3321** [comment]
moi aussi

**Comment by colinhartigan** [comment]
you need to own skins
