### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shinraof** [colinhartigan/valorant-inventory-manager#94]
![dgfjdfgj](https://user-images.githubusercontent.com/115156632/194304005-c805ac7d-0bc4-41db-acce-9e43fd515ca9.PNG)

Happens whenever I start valorant and try and use the site.

**Comment by colinhartigan** [comment]
use the [latest version](https://github.com/colinhartigan/valorant-inventory-manager/releases/tag/v1.1.1)
